name: Build appimage
on: [push]
jobs:
  coderibbon-theia-appimage:
    name: Build CodeRibbon-Theia appimage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install building dependencies
        run: sudo apt update &&
             sudo apt -y install python3-setuptools libx11-dev libxkbfile-dev  

      - run: yarn install

      - run: yarn download:plugins

      - run: yarn build:electron

      - run: yarn electron package --linux

      - uses: actions/upload-artifact@v4
        with:
          path: electron-app/dist/*.AppImage
          name: coderibbon-electron