name: Build on OSX

on:
  workflow_dispatch:

jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install building dependencies
        run: brew install python-setuptools libx11 libxkbfile

      - name: Install Yarn
        run: yarn install

      - name: Download default plugins
        run: yarn download:plugins

      - name: Build Browser version
        run: yarn build:browser
      
      - name: Build Electron version
        run: yarn build:electron
